export const visibleStyles = {
  color: "black",
  position: "fixed",
  zIndex: "11",
  top: "14%",
  left: "46%",
  width: "10.5%",
  height: "6%",
  border: "none",
  borderRadius: "5rem",
  background: "rgb(255, 248, 248)",
  boxShadow: "2px 2px rgb(243, 242, 243)",
};
export const CardDescription = [
  {
    id: "1",
    title: "Digital Marketing Job",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "A digital marketing job in e-commerce.",
    longDescription:
      "An opportunity for BBA/MBA majors to pursue a career in digital marketing in one of the most sucessfull business companies in Pakistan",
    listingDate: "1 month ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Sindh",
    city: "Karachi",
    Img: "/images/Img5.webp",
    price: "45,000",
    location: "Teen Talwaar",
  },
  {
    id: "2",
    title: "Book Shelf",
    Img: "/images/Img6.webp",
    price: "90,000",
    location: "Choburji",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A fancy wooden bookshelf.",
    longDescription:
      "Built with high quality timber and carpented with hand, its a beautiful fancy wooden bookshelf.",
    listingDate: "3 months ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "3",
    title: "Black Sofa with Table",
    Img: "/images/Img10.webp",
    price: "18,000",
    location: "Maleer Chowk",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A sofa and a table set.",
    longDescription:
      "A black color table with a cushion sofa colored maroon, used for 2 years.",
    listingDate: "1 week ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "4",
    title: "Apple Airpods Pro",
    Img: "/images/Img11.webp",
    price: "29,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "Apple Airpods",
    shortDescription: "2 months used airpods pro.",
    longDescription:
      "Black colored good quality apple airpods, selling to get new ones.",
    listingDate: "3 days ago",
    sellerName: "Abdullah",
    membershipDate: "August, 2022",
    phoneNum: "3020034001",
    province: "Federal Territory",
    city: "Islamabad",
  },
  {
    id: "5",
    title: "HP Pavillion Tablet",
    Img: "/images/Img12.webp",
    price: "80,000",
    location: "Shahadrah",
    featured: "yes",
    mainCategory: "Tech Items",
    productType: "Tablet",
    shortDescription: "4/64 GB HP tablet.",
    longDescription:
      "HP Pavillion 2019 model tablet, 4/64 GB RAM/ROM, 5G supported.",
    listingDate: "11 days ago",
    sellerName: "Rana Sana Wasiq",
    membershipDate: "December, 2021",
    phoneNum: "3021200001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "6",
    title: "Medical Staff Required",
    Img: "/images/Img19.webp",
    price: "50,000 (salary)",
    location: "Gulberg 3",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "Medical Staff required for a hospital.",
    longDescription:
      "Nurse, Compounder and ward boys required for Salim Int Hospital Lahore, Pharmacists can apply as well.",
    listingDate: "1 day ago",
    sellerName: "Sabahat Firms",
    membershipDate: "January, 2021",
    phoneNum: "3020990001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "7",
    title: "Q Mobile Tablet",
    Img: "/images/Img17.webp",
    price: "30,000",
    location: "Burj Chowk",
    mainCategory: "Tech Items",
    productType: "Tablets",
    shortDescription: "Q Mobile Tablet 3/32 GB.",
    longDescription:
      "Q Tab 3/32 GB 4G supported, 8px front and 13px back camera, gyro supported.",
    listingDate: "5 days ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "8",
    title: "Grockery",
    Img: "/images/Img18.webp",
    price: "8,000",
    location: "Chowrangi",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Grockery",
    shortDescription: "Grockery for low income households.",
    longDescription:
      "Customized grockery buckets in low price, product quality varies.",
    listingDate: "1 week ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "9",
    title: "Oppo A1 Pro",
    Img: "/images/Img15.webp",
    price: "62,000",
    location: "DC Chowk",
    mainCategory: "Tech Items",
    productType: "Smartphones",
    shortDescription: "Oppo A1 pro 6/128 GB good condition.",
    longDescription:
      "PTA approved good quality, no fault, no damage, all hardware working properly.",
    listingDate: "1 month ago",
    sellerName: "Salman Mobiles",
    membershipDate: "March, 2021",
    phoneNum: "3020012001",
    province: "Punjab",
    city: "Bahawalpur",
  },
  {
    id: "10",
    title: "Persian White Kitten",
    Img: "/images/Img20.webp",
    price: "33,000",
    location: "Lake City",
    featured: "yes",
    mainCategory: "Pets",
    productType: "Cats",
    shortDescription: "A white persian male kitten.",
    longDescription:
      "Aged 3 months, white persian male kitten blue eyed, pure breed, selling because no more room for pets in my home",
    listingDate: "4 days ago",
    sellerName: "SFarzan",
    membershipDate: "January, 2022",
    phoneNum: "3020066001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "11",
    title: "VR Glasses",
    Img: "/images/Img21.webp",
    price: "94,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "VR Glasses",
    shortDescription: "MR Goggles, matt finish, brand:Tenoire.",
    longDescription:
      "Tenoire VR headset for gaming/metaverse, seal packed, no fault, supports PSVR and Windows VR as well.",
    listingDate: "1 month ago",
    sellerName: "Sohail Tech",
    membershipDate: "January, 2018",
    phoneNum: "3020230001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "12",
    title: "Chipset",
    Img: "/images/Img23.webp",
    price: "6,000",
    location: "Fayaz e Madina",
    mainCategory: "Tech Items",
    productType: "Chips",
    shortDescription: "An arduino chipset for sale.",
    longDescription:
      "Arduino 4me333z4 chipset for hardware programming, imported.",
    listingDate: "2 months ago",
    sellerName: "Abubakar Tech",
    membershipDate: "August, 2021",
    phoneNum: "3020091201",
    province: "Punjab",
    city: "Bhakkar",
  },
  {
    id: "13",
    title: "Grockery",
    Img: "/images/Img24.webp",
    price: "27,000",
    location: "Noorpur Colony",
    mainCategory: "Household Items",
    productType: "Grockery",
    shortDescription: "Grockery for low income households.",
    longDescription:
      "Customized grockery buckets in low price, product quality varies.",
    listingDate: "1 week ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Punjab",
    city: "Pakpattan",
  },
  {
    id: "14",
    title: "Tech House Job",
    Img: "/images/Img28.webp",
    price: "76,000 (salary)",
    location: "F-9",
    featured: "yes",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "A tech WFH job.",
    longDescription:
      "An opportunity for CS majors majors to pursue a career in web development while working from home",
    listingDate: "1 month ago",
    sellerName: "Saleh Software House",
    membershipDate: "May, 2021",
    phoneNum: "3020000001",
    province: "Federal Territory",
    city: "Islamabad",
  },
  {
    id: "15",
    title: "Meds for Furniture",
    Img: "/images/Img29.webp",
    price: "9,00",
    location: "Numaish Chowk",
    featured: "yes",
    mainCategory: "Chemicals and Meds",
    productType: "Meds",
    shortDescription: "Meds for fruniture protection.",
    longDescription:
      "Non toxic furniture polish to keep it safe from degradation.",
    listingDate: "1 day ago",
    sellerName: "Farooq Woods",
    membershipDate: "May, 2021",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Multan",
  },
  {
    id: "16",
    title: "Toy Piano for Babies",
    Img: "/images/Img30.webp",
    price: "4,500",
    location: "Emporium",
    featured: "yes",
    mainCategory: "Baby Products",
    productType: "Toys",
    shortDescription: "Toy piano fitted on a chair.",
    longDescription:
      "Rechargable piano for kids fitted on a chair for easy support of toddlers, brand new.",
    listingDate: "1 month ago",
    sellerName: "Farzand Products",
    membershipDate: "May, 2021",
    phoneNum: "3020054101",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "17",
    title: "Residential Plot For Sale in White City",
    Img: "/images/Img31.webp",
    price: "2,750,000",
    location: "Gulberg 3",
    featured: "yes",
    mainCategory: "Properties",
    productType: "Houses",
    shortDescription: "1 Kanal Facing Park Beautiful Location",
    longDescription:
      "1 canal house, newly built with premium location, 3 bedrooms with attached bathrooms, a lawn and a fancy kitchen with marble ceiling",
    listingDate: "4 weeks ago",
    sellerName: "Khan Associates",
    membershipDate: "November, 2020",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "18",
    title: "Book Shelf",
    Img: "/images/Img6.webp",
    price: "90,000",
    location: "Choburji",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A fancy wooden bookshelf.",
    longDescription:
      "Built with high quality timber and carpented with hand, its a beautiful fancy wooden bookshelf.",
    listingDate: "3 months ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "19",
    title: "Black Sofa with Table",
    Img: "/images/Img10.webp",
    price: "18,000",
    location: "Maleer Chowk",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A sofa and a table set.",
    longDescription:
      "A black color table with a cushion sofa colored maroon, used for 2 years.",
    listingDate: "1 week ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Punjab",
    city: "Gujranwala",
  },
  {
    id: "20",
    title: "Persian White Kitten",
    Img: "/images/Img20.webp",
    price: "33,000",
    location: "Lake City",
    featured: "yes",
    mainCategory: "Pets",
    productType: "Cats",
    shortDescription: "A white persian male kitten.",
    longDescription:
      "Aged 3 months, white persian male kitten blue eyed, pure breed, selling because no more room for pets in my home",
    listingDate: "4 days ago",
    sellerName: "SFarzan",
    membershipDate: "January, 2022",
    phoneNum: "3020066001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "21",
    title: "VR Glasses",
    Img: "/images/Img21.webp",
    price: "94,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "VR Glasses",
    shortDescription: "MR Goggles, matt finish, brand:Tenoire.",
    longDescription:
      "Tenoire VR headset for gaming/metaverse, seal packed, no fault, supports PSVR and Windows VR as well.",
    listingDate: "1 month ago",
    sellerName: "Sohail Tech",
    membershipDate: "January, 2018",
    phoneNum: "3020230001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "22",
    title: "HP Pavillion Tablet",
    Img: "/images/Img12.webp",
    price: "80,000",
    location: "Shahadrah",
    featured: "yes",
    mainCategory: "Tech Items",
    productType: "Tablet",
    shortDescription: "4/64 GB HP tablet.",
    longDescription:
      "HP Pavillion 2019 model tablet, 4/64 GB RAM/ROM, 5G supported.",
    listingDate: "11 days ago",
    sellerName: "Rana Sana Wasiq",
    membershipDate: "December, 2021",
    phoneNum: "3021200001",
    province: "Punjab",
    city: "Lahore",
  },
];
export const CardDescription2 = [
  {
    id: "1",
    title: "Digital Marketing Job",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "A digital marketing job in e-commerce.",
    longDescription:
      "An opportunity for BBA/MBA majors to pursue a career in digital marketing in one of the most sucessfull business companies in Pakistan",
    listingDate: "1 month ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Sindh",
    city: "Karachi",
    Img: "/images/Img5.webp",
    price: "45,000",
    location: "Teen Talwaar",
  },
  {
    id: "2",
    title: "Book Shelf",
    Img: "/images/Img6.webp",
    price: "90,000",
    location: "Choburji",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A fancy wooden bookshelf.",
    longDescription:
      "Built with high quality timber and carpented with hand, its a beautiful fancy wooden bookshelf.",
    listingDate: "3 months ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "3",
    title: "Black Sofa with Table",
    Img: "/images/Img10.webp",
    price: "18,000",
    location: "Maleer Chowk",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A sofa and a table set.",
    longDescription:
      "A black color table with a cushion sofa colored maroon, used for 2 years.",
    listingDate: "1 week ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "4",
    title: "Apple Airpods Pro",
    Img: "/images/Img11.webp",
    price: "29,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "Apple Airpods",
    shortDescription: "2 months used airpods pro.",
    longDescription:
      "Black colored good quality apple airpods, selling to get new ones.",
    listingDate: "3 days ago",
    sellerName: "Abdullah",
    membershipDate: "August, 2022",
    phoneNum: "3020034001",
    province: "Federal Territory",
    city: "Islamabad",
  },
  {
    id: "5",
    title: "HP Pavillion Tablet",
    Img: "/images/Img12.webp",
    price: "80,000",
    location: "Shahadrah",
    featured: "yes",
    mainCategory: "Tech Items",
    productType: "Tablet",
    shortDescription: "4/64 GB HP tablet.",
    longDescription:
      "HP Pavillion 2019 model tablet, 4/64 GB RAM/ROM, 5G supported.",
    listingDate: "11 days ago",
    sellerName: "Rana Sana Wasiq",
    membershipDate: "December, 2021",
    phoneNum: "3021200001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "6",
    title: "Medical Staff Required",
    Img: "/images/Img19.webp",
    price: "50,000 (salary)",
    location: "Gulberg 3",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "Medical Staff required for a hospital.",
    longDescription:
      "Nurse, Compounder and ward boys required for Salim Int Hospital Lahore, Pharmacists can apply as well.",
    listingDate: "1 day ago",
    sellerName: "Sabahat Firms",
    membershipDate: "January, 2021",
    phoneNum: "3020990001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "7",
    title: "Q Mobile Tablet",
    Img: "/images/Img17.webp",
    price: "30,000",
    location: "Burj Chowk",
    mainCategory: "Tech Items",
    productType: "Tablets",
    shortDescription: "Q Mobile Tablet 3/32 GB.",
    longDescription:
      "Q Tab 3/32 GB 4G supported, 8px front and 13px back camera, gyro supported.",
    listingDate: "5 days ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "8",
    title: "Grockery",
    Img: "/images/Img18.webp",
    price: "8,000",
    location: "Chowrangi",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Grockery",
    shortDescription: "Grockery for low income households.",
    longDescription:
      "Customized grockery buckets in low price, product quality varies.",
    listingDate: "1 week ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "9",
    title: "Oppo A1 Pro",
    Img: "/images/Img15.webp",
    price: "62,000",
    location: "DC Chowk",
    mainCategory: "Tech Items",
    productType: "Smartphones",
    shortDescription: "Oppo A1 pro 6/128 GB good condition.",
    longDescription:
      "PTA approved good quality, no fault, no damage, all hardware working properly.",
    listingDate: "1 month ago",
    sellerName: "Salman Mobiles",
    membershipDate: "March, 2021",
    phoneNum: "3020012001",
    province: "Punjab",
    city: "Bahawalpur",
  },
  {
    id: "10",
    title: "Persian White Kitten",
    Img: "/images/Img20.webp",
    price: "33,000",
    location: "Lake City",
    featured: "yes",
    mainCategory: "Pets",
    productType: "Cats",
    shortDescription: "A white persian male kitten.",
    longDescription:
      "Aged 3 months, white persian male kitten blue eyed, pure breed, selling because no more room for pets in my home",
    listingDate: "4 days ago",
    sellerName: "SFarzan",
    membershipDate: "January, 2022",
    phoneNum: "3020066001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "11",
    title: "VR Glasses",
    Img: "/images/Img21.webp",
    price: "94,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "VR Glasses",
    shortDescription: "MR Goggles, matt finish, brand:Tenoire.",
    longDescription:
      "Tenoire VR headset for gaming/metaverse, seal packed, no fault, supports PSVR and Windows VR as well.",
    listingDate: "1 month ago",
    sellerName: "Sohail Tech",
    membershipDate: "January, 2018",
    phoneNum: "3020230001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "12",
    title: "Chipset",
    Img: "/images/Img23.webp",
    price: "6,000",
    location: "Fayaz e Madina",
    mainCategory: "Tech Items",
    productType: "Chips",
    shortDescription: "An arduino chipset for sale.",
    longDescription:
      "Arduino 4me333z4 chipset for hardware programming, imported.",
    listingDate: "2 months ago",
    sellerName: "Abubakar Tech",
    membershipDate: "August, 2021",
    phoneNum: "3020091201",
    province: "Punjab",
    city: "Bhakkar",
  },
  {
    id: "13",
    title: "Grockery",
    Img: "/images/Img24.webp",
    price: "27,000",
    location: "Noorpur Colony",
    mainCategory: "Household Items",
    productType: "Grockery",
    shortDescription: "Grockery for low income households.",
    longDescription:
      "Customized grockery buckets in low price, product quality varies.",
    listingDate: "1 week ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Punjab",
    city: "Pakpattan",
  },
  {
    id: "14",
    title: "Tech House Job",
    Img: "/images/Img28.webp",
    price: "76,000 (salary)",
    location: "F-9",
    featured: "yes",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "A tech WFH job.",
    longDescription:
      "An opportunity for CS majors majors to pursue a career in web development while working from home",
    listingDate: "1 month ago",
    sellerName: "Saleh Software House",
    membershipDate: "May, 2021",
    phoneNum: "3020000001",
    province: "Federal Territory",
    city: "Islamabad",
  },
  {
    id: "15",
    title: "Meds for Furniture",
    Img: "/images/Img29.webp",
    price: "9,00",
    location: "Numaish Chowk",
    featured: "yes",
    mainCategory: "Chemicals and Meds",
    productType: "Meds",
    shortDescription: "Meds for fruniture protection.",
    longDescription:
      "Non toxic furniture polish to keep it safe from degradation.",
    listingDate: "1 day ago",
    sellerName: "Farooq Woods",
    membershipDate: "May, 2021",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Multan",
  },
  {
    id: "16",
    title: "Toy Piano for Babies",
    Img: "/images/Img30.webp",
    price: "4,500",
    location: "Emporium",
    featured: "yes",
    mainCategory: "Baby Products",
    productType: "Toys",
    shortDescription: "Toy piano fitted on a chair.",
    longDescription:
      "Rechargable piano for kids fitted on a chair for easy support of toddlers, brand new.",
    listingDate: "1 month ago",
    sellerName: "Farzand Products",
    membershipDate: "May, 2021",
    phoneNum: "3020054101",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "17",
    title: "Residential Plot For Sale in White City",
    Img: "/images/Img31.webp",
    price: "2,750,000",
    location: "Gulberg 3",
    featured: "yes",
    mainCategory: "Properties",
    productType: "Houses",
    shortDescription: "1 Kanal Facing Park Beautiful Location",
    longDescription:
      "1 canal house, newly built with premium location, 3 bedrooms with attached bathrooms, a lawn and a fancy kitchen with marble ceiling",
    listingDate: "4 weeks ago",
    sellerName: "Khan Associates",
    membershipDate: "November, 2020",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "18",
    title: "Book Shelf",
    Img: "/images/Img6.webp",
    price: "90,000",
    location: "Choburji",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A fancy wooden bookshelf.",
    longDescription:
      "Built with high quality timber and carpented with hand, its a beautiful fancy wooden bookshelf.",
    listingDate: "3 months ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "19",
    title: "Black Sofa with Table",
    Img: "/images/Img10.webp",
    price: "18,000",
    location: "Maleer Chowk",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A sofa and a table set.",
    longDescription:
      "A black color table with a cushion sofa colored maroon, used for 2 years.",
    listingDate: "1 week ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Punjab",
    city: "Gujranwala",
  },
  {
    id: "20",
    title: "Persian White Kitten",
    Img: "/images/Img20.webp",
    price: "33,000",
    location: "Lake City",
    featured: "yes",
    mainCategory: "Pets",
    productType: "Cats",
    shortDescription: "A white persian male kitten.",
    longDescription:
      "Aged 3 months, white persian male kitten blue eyed, pure breed, selling because no more room for pets in my home",
    listingDate: "4 days ago",
    sellerName: "SFarzan",
    membershipDate: "January, 2022",
    phoneNum: "3020066001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "21",
    title: "VR Glasses",
    Img: "/images/Img21.webp",
    price: "94,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "VR Glasses",
    shortDescription: "MR Goggles, matt finish, brand:Tenoire.",
    longDescription:
      "Tenoire VR headset for gaming/metaverse, seal packed, no fault, supports PSVR and Windows VR as well.",
    listingDate: "1 month ago",
    sellerName: "Sohail Tech",
    membershipDate: "January, 2018",
    phoneNum: "3020230001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "22",
    title: "HP Pavillion Tablet",
    Img: "/images/Img12.webp",
    price: "80,000",
    location: "Shahadrah",
    featured: "yes",
    mainCategory: "Tech Items",
    productType: "Tablet",
    shortDescription: "4/64 GB HP tablet.",
    longDescription:
      "HP Pavillion 2019 model tablet, 4/64 GB RAM/ROM, 5G supported.",
    listingDate: "11 days ago",
    sellerName: "Rana Sana Wasiq",
    membershipDate: "December, 2021",
    phoneNum: "3021200001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "23",
    title: "Medical Staff Required",
    Img: "/images/Img19.webp",
    price: "50,000 (salary)",
    location: "Gulberg 3",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "Medical Staff required for a hospital.",
    longDescription:
      "Nurse, Compounder and ward boys required for Salim Int Hospital Lahore, Pharmacists can apply as well.",
    listingDate: "1 day ago",
    sellerName: "Sabahat Firms",
    membershipDate: "January, 2021",
    phoneNum: "3020990001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "24",
    title: "Q Mobile Tablet",
    Img: "/images/Img17.webp",
    price: "30,000",
    location: "Burj Chowk",
    mainCategory: "Tech Items",
    productType: "Tablets",
    shortDescription: "Q Mobile Tablet 3/32 GB.",
    longDescription:
      "Q Tab 3/32 GB 4G supported, 8px front and 13px back camera, gyro supported.",
    listingDate: "5 days ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "25",
    title: "Grockery",
    Img: "/images/Img18.webp",
    price: "8,000",
    location: "Chowrangi",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Grockery",
    shortDescription: "Grockery for low income households.",
    longDescription:
      "Customized grockery buckets in low price, product quality varies.",
    listingDate: "1 week ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Sindh",
    city: "Karachi",
  },
  {
    id: "26",
    title: "Oppo A1 Pro",
    Img: "/images/Img15.webp",
    price: "62,000",
    location: "DC Chowk",
    mainCategory: "Tech Items",
    productType: "Smartphones",
    shortDescription: "Oppo A1 pro 6/128 GB good condition.",
    longDescription:
      "PTA approved good quality, no fault, no damage, all hardware working properly.",
    listingDate: "1 month ago",
    sellerName: "Salman Mobiles",
    membershipDate: "March, 2021",
    phoneNum: "3020012001",
    province: "Punjab",
    city: "Bahawalpur",
  },
  {
    id: "27",
    title: "Persian White Kitten",
    Img: "/images/Img20.webp",
    price: "33,000",
    location: "Lake City",
    featured: "yes",
    mainCategory: "Pets",
    productType: "Cats",
    shortDescription: "A white persian male kitten.",
    longDescription:
      "Aged 3 months, white persian male kitten blue eyed, pure breed, selling because no more room for pets in my home",
    listingDate: "4 days ago",
    sellerName: "SFarzan",
    membershipDate: "January, 2022",
    phoneNum: "3020066001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "28",
    title: "VR Glasses",
    Img: "/images/Img21.webp",
    price: "94,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "VR Glasses",
    shortDescription: "MR Goggles, matt finish, brand:Tenoire.",
    longDescription:
      "Tenoire VR headset for gaming/metaverse, seal packed, no fault, supports PSVR and Windows VR as well.",
    listingDate: "1 month ago",
    sellerName: "Sohail Tech",
    membershipDate: "January, 2018",
    phoneNum: "3020230001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "29",
    title: "Chipset",
    Img: "/images/Img23.webp",
    price: "6,000",
    location: "Fayaz e Madina",
    mainCategory: "Tech Items",
    productType: "Chips",
    shortDescription: "An arduino chipset for sale.",
    longDescription:
      "Arduino 4me333z4 chipset for hardware programming, imported.",
    listingDate: "2 months ago",
    sellerName: "Abubakar Tech",
    membershipDate: "August, 2021",
    phoneNum: "3020091201",
    province: "Punjab",
    city: "Bhakkar",
  },
  {
    id: "30",
    title: "Grockery",
    Img: "/images/Img24.webp",
    price: "27,000",
    location: "Pakpattan",
    mainCategory: "Household Items",
    productType: "Grockery",
    shortDescription: "Grockery for low income households.",
    longDescription:
      "Customized grockery buckets in low price, product quality varies.",
    listingDate: "1 week ago",
    sellerName: "Sabahat Firms",
    membershipDate: "August, 2021",
    phoneNum: "3020000001",
    province: "Punjab",
    city: "Pakpattan",
  },
  {
    id: "31",
    title: "Tech House Job",
    Img: "/images/Img28.webp",
    price: "76,000 (salary)",
    location: "F-9",
    featured: "yes",
    mainCategory: "Jobs",
    productType: "Services",
    shortDescription: "A tech WFH job.",
    longDescription:
      "An opportunity for CS majors majors to pursue a career in web development while working from home",
    listingDate: "1 month ago",
    sellerName: "Saleh Software House",
    membershipDate: "May, 2021",
    phoneNum: "3020000001",
    province: "Federal Territory",
    city: "Islamabad",
  },
  {
    id: "32",
    title: "Meds for Furniture",
    Img: "/images/Img29.webp",
    price: "9,00",
    location: "Numaish Chowk",
    featured: "yes",
    mainCategory: "Chemicals and Meds",
    productType: "Meds",
    shortDescription: "Meds for fruniture protection.",
    longDescription:
      "Non toxic furniture polish to keep it safe from degradation.",
    listingDate: "1 day ago",
    sellerName: "Farooq Woods",
    membershipDate: "May, 2021",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Multan",
  },
  {
    id: "33",
    title: "Toy Piano for Babies",
    Img: "/images/Img30.webp",
    price: "4,500",
    location: "Emporium",
    featured: "yes",
    mainCategory: "Baby Products",
    productType: "Toys",
    shortDescription: "Toy piano fitted on a chair.",
    longDescription:
      "Rechargable piano for kids fitted on a chair for easy support of toddlers, brand new.",
    listingDate: "1 month ago",
    sellerName: "Farzand Products",
    membershipDate: "May, 2021",
    phoneNum: "3020054101",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "34",
    title: "Residential Plot For Sale in White City",
    Img: "/images/Img31.webp",
    price: "2,750,000",
    location: "Gulberg 3",
    featured: "yes",
    mainCategory: "Properties",
    productType: "Houses",
    shortDescription: "1 Kanal Facing Park Beautiful Location",
    longDescription:
      "1 canal house, newly built with premium location, 3 bedrooms with attached bathrooms, a lawn and a fancy kitchen with marble ceiling",
    listingDate: "4 weeks ago",
    sellerName: "Khan Associates",
    membershipDate: "November, 2020",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "35",
    title: "Book Shelf",
    Img: "/images/Img6.webp",
    price: "90,000",
    location: "Choburji",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A fancy wooden bookshelf.",
    longDescription:
      "Built with high quality timber and carpented with hand, its a beautiful fancy wooden bookshelf.",
    listingDate: "3 months ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "36",
    title: "Black Sofa with Table",
    Img: "/images/Img10.webp",
    price: "18,000",
    location: "Maleer Chowk",
    featured: "yes",
    mainCategory: "Household Items",
    productType: "Furniture",
    shortDescription: "A sofa and a table set.",
    longDescription:
      "A black color table with a cushion sofa colored maroon, used for 2 years.",
    listingDate: "1 week ago",
    sellerName: "Saboor Woods",
    membershipDate: "August, 2018",
    phoneNum: "3020002301",
    province: "Punjab",
    city: "Gujranwala",
  },
  {
    id: "37",
    title: "Persian White Kitten",
    Img: "/images/Img20.webp",
    price: "33,000",
    location: "Lake City",
    featured: "yes",
    mainCategory: "Pets",
    productType: "Cats",
    shortDescription: "A white persian male kitten.",
    longDescription:
      "Aged 3 months, white persian male kitten blue eyed, pure breed, selling because no more room for pets in my home",
    listingDate: "4 days ago",
    sellerName: "SFarzan",
    membershipDate: "January, 2022",
    phoneNum: "3020066001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "38",
    title: "VR Glasses",
    Img: "/images/Img21.webp",
    price: "94,000",
    location: "DHA",
    mainCategory: "Tech Items",
    productType: "VR Glasses",
    shortDescription: "MR Goggles, matt finish, brand:Tenoire.",
    longDescription:
      "Tenoire VR headset for gaming/metaverse, seal packed, no fault, supports PSVR and Windows VR as well.",
    listingDate: "1 month ago",
    sellerName: "Sohail Tech",
    membershipDate: "January, 2018",
    phoneNum: "3020230001",
    province: "Punjab",
    city: "Lahore",
  },
  {
    id: "39",
    title: "Home for Sale",
    Img: "/images/Img2.webp",
    price: "2,750,000",
    location: "Gulberg 3",
    featured: "yes",
    mainCategory: "Properties",
    productType: "Houses",
    shortDescription: "1 Kanal Facing Park Beautiful Location",
    longDescription:
      "1 canal house, newly built with premium location, 3 bedrooms with attached bathrooms, a lawn and a fancy kitchen with marble ceiling",
    listingDate: "4 weeks ago",
    sellerName: "Khan Associates",
    membershipDate: "November, 2020",
    phoneNum: "3020123001",
    province: "Punjab",
    city: "Lahore",
  },
];

export function getProductById(id) {
  return CardDescription2.find((product) => product.id === id);
}
